// <auto-generated />
using Investa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Investa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260709120000_AddPaidActionPricingRules")]
    partial class AddPaidActionPricingRules
    {
    }
}
