// <auto-generated />
using System;
using Investa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Investa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130120000_BE-XXX_AddRequestTypeToInvestmentRequests")]
    partial class BEXXXAddRequestTypeToInvestmentRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is contained in ApplicationDbContextModelSnapshot.
            // This method is intentionally left minimal to register the migration metadata.
        }
    }
}
