// File generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  // Android config — values sourced from google-services.json (project: investa-58438)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUXlhpReSb5PsBmDJZ0ZN7EUuUYSO334',
    appId: '1:997573340268:android:7627c9a8aae07d928d7c49',
    messagingSenderId: '997573340268',
    projectId: 'investa-58438',
    storageBucket: 'investa-58438.firebasestorage.app',
  );

  // iOS config — populate from GoogleService-Info.plist when iOS build is added
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUXlhpReSb5PsBmDJZ0ZN7EUuUYSO334',
    appId: '1:997573340268:ios:7627c9a8aae07d928d7c49',
    messagingSenderId: '997573340268',
    projectId: 'investa-58438',
    storageBucket: 'investa-58438.firebasestorage.app',
    iosBundleId: 'investa_founder.a010',
  );

  // Web config — populate with values from Firebase Console → Project settings → Web app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUXlhpReSb5PsBmDJZ0ZN7EUuUYSO334',
    appId: '1:997573340268:web:7627c9a8aae07d928d7c49',
    messagingSenderId: '997573340268',
    projectId: 'investa-58438',
    authDomain: 'investa-58438.firebaseapp.com',
    storageBucket: 'investa-58438.firebasestorage.app',
  );
}
