// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class AuthUser {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class UserInfo {
    private @NonNull String uid;

    public @NonNull String getUid() {
      return uid;
    }

    public void setUid(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"uid\" is null.");
      }
      this.uid = setterArg;
    }

    private @Nullable String phoneNumber;

    public @Nullable String getPhoneNumber() {
      return phoneNumber;
    }

    public void setPhoneNumber(@Nullable String setterArg) {
      this.phoneNumber = setterArg;
    }

    private @Nullable String email;

    public @Nullable String getEmail() {
      return email;
    }

    public void setEmail(@Nullable String setterArg) {
      this.email = setterArg;
    }

    private @Nullable String displayName;

    public @Nullable String getDisplayName() {
      return displayName;
    }

    public void setDisplayName(@Nullable String setterArg) {
      this.displayName = setterArg;
    }

    private @NonNull Boolean isAnonymous;

    public @NonNull Boolean getIsAnonymous() {
      return isAnonymous;
    }

    public void setIsAnonymous(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isAnonymous\" is null.");
      }
      this.isAnonymous = setterArg;
    }

    private @NonNull Boolean isEmailVerified;

    public @NonNull Boolean getIsEmailVerified() {
      return isEmailVerified;
    }

    public void setIsEmailVerified(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isEmailVerified\" is null.");
      }
      this.isEmailVerified = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    UserInfo() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      UserInfo that = (UserInfo) o;
      return uid.equals(that.uid) && Objects.equals(phoneNumber, that.phoneNumber) && Objects.equals(email, that.email) && Objects.equals(displayName, that.displayName) && isAnonymous.equals(that.isAnonymous) && isEmailVerified.equals(that.isEmailVerified);
    }

    @Override
    public int hashCode() {
      return Objects.hash(uid, phoneNumber, email, displayName, isAnonymous, isEmailVerified);
    }

    public static final class Builder {

      private @Nullable String uid;

      @CanIgnoreReturnValue
      public @NonNull Builder setUid(@NonNull String setterArg) {
        this.uid = setterArg;
        return this;
      }

      private @Nullable String phoneNumber;

      @CanIgnoreReturnValue
      public @NonNull Builder setPhoneNumber(@Nullable String setterArg) {
        this.phoneNumber = setterArg;
        return this;
      }

      private @Nullable String email;

      @CanIgnoreReturnValue
      public @NonNull Builder setEmail(@Nullable String setterArg) {
        this.email = setterArg;
        return this;
      }

      private @Nullable String displayName;

      @CanIgnoreReturnValue
      public @NonNull Builder setDisplayName(@Nullable String setterArg) {
        this.displayName = setterArg;
        return this;
      }

      private @Nullable Boolean isAnonymous;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsAnonymous(@NonNull Boolean setterArg) {
        this.isAnonymous = setterArg;
        return this;
      }

      private @Nullable Boolean isEmailVerified;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsEmailVerified(@NonNull Boolean setterArg) {
        this.isEmailVerified = setterArg;
        return this;
      }

      public @NonNull UserInfo build() {
        UserInfo pigeonReturn = new UserInfo();
        pigeonReturn.setUid(uid);
        pigeonReturn.setPhoneNumber(phoneNumber);
        pigeonReturn.setEmail(email);
        pigeonReturn.setDisplayName(displayName);
        pigeonReturn.setIsAnonymous(isAnonymous);
        pigeonReturn.setIsEmailVerified(isEmailVerified);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(uid);
      toListResult.add(phoneNumber);
      toListResult.add(email);
      toListResult.add(displayName);
      toListResult.add(isAnonymous);
      toListResult.add(isEmailVerified);
      return toListResult;
    }

    static @NonNull UserInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      UserInfo pigeonResult = new UserInfo();
      Object uid = pigeonVar_list.get(0);
      pigeonResult.setUid((String) uid);
      Object phoneNumber = pigeonVar_list.get(1);
      pigeonResult.setPhoneNumber((String) phoneNumber);
      Object email = pigeonVar_list.get(2);
      pigeonResult.setEmail((String) email);
      Object displayName = pigeonVar_list.get(3);
      pigeonResult.setDisplayName((String) displayName);
      Object isAnonymous = pigeonVar_list.get(4);
      pigeonResult.setIsAnonymous((Boolean) isAnonymous);
      Object isEmailVerified = pigeonVar_list.get(5);
      pigeonResult.setIsEmailVerified((Boolean) isEmailVerified);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class UserDetails {
    private @NonNull UserInfo userInfo;

    public @NonNull UserInfo getUserInfo() {
      return userInfo;
    }

    public void setUserInfo(@NonNull UserInfo setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"userInfo\" is null.");
      }
      this.userInfo = setterArg;
    }

    private @NonNull List<Map<String, Object>> providerData;

    public @NonNull List<Map<String, Object>> getProviderData() {
      return providerData;
    }

    public void setProviderData(@NonNull List<Map<String, Object>> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"providerData\" is null.");
      }
      this.providerData = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    UserDetails() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      UserDetails that = (UserDetails) o;
      return userInfo.equals(that.userInfo) && providerData.equals(that.providerData);
    }

    @Override
    public int hashCode() {
      return Objects.hash(userInfo, providerData);
    }

    public static final class Builder {

      private @Nullable UserInfo userInfo;

      @CanIgnoreReturnValue
      public @NonNull Builder setUserInfo(@NonNull UserInfo setterArg) {
        this.userInfo = setterArg;
        return this;
      }

      private @Nullable List<Map<String, Object>> providerData;

      @CanIgnoreReturnValue
      public @NonNull Builder setProviderData(@NonNull List<Map<String, Object>> setterArg) {
        this.providerData = setterArg;
        return this;
      }

      public @NonNull UserDetails build() {
        UserDetails pigeonReturn = new UserDetails();
        pigeonReturn.setUserInfo(userInfo);
        pigeonReturn.setProviderData(providerData);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(userInfo);
      toListResult.add(providerData);
      return toListResult;
    }

    static @NonNull UserDetails fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      UserDetails pigeonResult = new UserDetails();
      Object userInfo = pigeonVar_list.get(0);
      pigeonResult.setUserInfo((UserInfo) userInfo);
      Object providerData = pigeonVar_list.get(1);
      pigeonResult.setProviderData((List<Map<String, Object>>) providerData);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return UserInfo.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return UserDetails.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof UserInfo) {
        stream.write(129);
        writeValue(stream, ((UserInfo) value).toList());
      } else if (value instanceof UserDetails) {
        stream.write(130);
        writeValue(stream, ((UserDetails) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface AuthBridge {

    @Nullable 
    UserDetails currentUser();

    /** The codec used by AuthBridge. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `AuthBridge` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable AuthBridge api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable AuthBridge api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_dark_app.AuthBridge.currentUser" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  UserDetails output = api.currentUser();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
