// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class UserInfo {
  UserInfo({
    required this.uid,
    this.phoneNumber,
    this.email,
    this.displayName,
    required this.isAnonymous,
    required this.isEmailVerified,
  });

  String uid;

  String? phoneNumber;

  String? email;

  String? displayName;

  bool isAnonymous;

  bool isEmailVerified;

  Object encode() {
    return <Object?>[
      uid,
      phoneNumber,
      email,
      displayName,
      isAnonymous,
      isEmailVerified,
    ];
  }

  static UserInfo decode(Object result) {
    result as List<Object?>;
    return UserInfo(
      uid: result[0]! as String,
      phoneNumber: result[1] as String?,
      email: result[2] as String?,
      displayName: result[3] as String?,
      isAnonymous: result[4]! as bool,
      isEmailVerified: result[5]! as bool,
    );
  }
}

class UserDetails {
  UserDetails({
    required this.userInfo,
    required this.providerData,
  });

  UserInfo userInfo;

  List<Map<String?, Object?>?> providerData;

  Object encode() {
    return <Object?>[
      userInfo,
      providerData,
    ];
  }

  static UserDetails decode(Object result) {
    result as List<Object?>;
    return UserDetails(
      userInfo: result[0]! as UserInfo,
      providerData: (result[1] as List<Object?>?)!.cast<Map<String?, Object?>?>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is UserInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is UserDetails) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return UserInfo.decode(readValue(buffer)!);
      case 130: 
        return UserDetails.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AuthBridge {
  /// Constructor for [AuthBridge].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AuthBridge({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<UserDetails?> currentUser() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_investor.AuthBridge.currentUser$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as UserDetails?);
    }
  }
}
